import scrollSuave from "./modules/scroll-suave.js";
import scrollDown from "./modules/scroll-anime.js";
import menuAcordion from "./modules/menu-acordion.js";
import tabMenuNav from "./modules/menu-nav.js";
import modalLogin from "./modules/modal.js";
import toltip from "./modules/toltip.js";
import dropDownMenu from "./modules/dropdown-menu.js";
import menuMobile from "./modules/menu-mobile.js";
import horarioFuncionamento from "./modules/horario-funcionamento.js";
import fetchAnimais from "./modules/fetch-animais.js";

scrollSuave();
scrollDown();
menuAcordion();
tabMenuNav();
modalLogin();
toltip();
dropDownMenu();
menuMobile();
horarioFuncionamento();
fetchAnimais();
